
// <summary>
// Represents the Domain of a State Enumeration, where the Domain is
// the Object generated by the TypeScript compiler for the State
// Enumeration which, for a numeric Enum, consists of the set of
// defined Values indexed by their Key and the set of Keys indexed
// by their Value. The 'stricter' version immediately below is not
// used in favor of the 'looser' version to avoid the complexities
// involved in Enum Generics.
// </summary>

// import { State } from '@state/domain/types/state/state.type';

// export type Domain<TState> =
//   {
//     [key: number]: string,
//     [key: string]: State<TState>
//   };

export type Domain = { [key: number | string]: number | string };
